# Generated by Django 5.2.16 on 2026-07-17 23:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("crm", "0002_initial"),
        ("files", "0001_initial"),
        ("projects", "0001_initial"),
        ("timetracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft_local", "Lokaler Entwurf"),
                            ("send_pending", "Übertragung läuft"),
                            ("draft_remote", "Lexware-Entwurf"),
                            ("open", "Offen"),
                            ("paid", "Bezahlt"),
                            ("overdue", "Überfällig"),
                            ("voided", "Storniert"),
                        ],
                        db_index=True,
                        default="draft_local",
                        max_length=20,
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(default="Rechnung", max_length=200)),
                ("introduction", models.TextField(blank=True)),
                ("remark", models.TextField(blank=True)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("payment_term_days", models.PositiveSmallIntegerField(default=14)),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("net", "Netto (zzgl. USt)"),
                            ("gross", "Brutto (inkl. USt)"),
                            ("vatfree", "Steuerfrei / Kleinunternehmer §19 UStG"),
                        ],
                        default="net",
                        max_length=20,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("19.00"),
                        help_text="Regelsteuersatz; bei Kleinunternehmer 0.",
                        max_digits=5,
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gross_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "open_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("paid_at", models.DateField(blank=True, null=True)),
                ("lexware_version", models.IntegerField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "grouping",
                    models.CharField(
                        choices=[
                            ("per_entry", "Einzelposition"),
                            ("per_day", "Pro Tag"),
                            ("per_service", "Pro Leistungsart"),
                            ("per_phase", "Pro Projektphase"),
                            ("per_task", "Pro Aufgabe"),
                            ("lump_sum", "Gesamtsumme"),
                        ],
                        default="per_service",
                        max_length=20,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="crm.client",
                    ),
                ),
                (
                    "pdf_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="files.storedfile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="projects.project",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("unit", models.CharField(default="Std.", max_length=30)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("19.00"), max_digits=5
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="invoicing.invoice",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceTimeEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("duration_seconds_taken", models.PositiveIntegerField()),
                ("amount_taken", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "invoice_cancelled",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_time_entries",
                        to="invoicing.invoice",
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="invoicing.invoiceline",
                    ),
                ),
                (
                    "time_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_links",
                        to="timetracking.timeentry",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.workspace",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["workspace", "status", "-created_at"],
                name="invoicing_i_workspa_bf0281_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["client", "status"], name="invoicing_i_client__c3e732_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicetimeentry",
            index=models.Index(
                fields=["invoice", "invoice_cancelled"],
                name="invoicing_i_invoice_06c41a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicetimeentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invoice_cancelled", False)),
                fields=("time_entry",),
                name="one_active_invoice_per_time_entry",
            ),
        ),
    ]
