# Generated by Django 5.2.16 on 2026-07-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetimeentry',
            name='source',
            field=models.CharField(choices=[('compose', 'Lokal zusammengestellt'), ('lexware_import', 'Aus Lexware zugeordnet')], default='compose', max_length=20),
        ),
    ]
