# Generated by Django 5.2.16 on 2026-07-18 00:27

import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedfile",
            name="storage",
            field=models.FileField(
                blank=True, max_length=500, upload_to=apps.files.models.upload_to
            ),
        ),
    ]
