# Generated by Django 5.2.16 on 2026-07-18 00:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxRuleSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tax_year", models.PositiveIntegerField(db_index=True)),
                ("rule_version", models.CharField(default="1", max_length=20)),
                ("valid_from", models.DateField()),
                (
                    "config",
                    models.JSONField(
                        help_text="Grundfreibetrag, Zonen, USt-Sätze, KV-Sätze, …"
                    ),
                ),
                (
                    "sources",
                    models.JSONField(
                        default=list, help_text="Quellenhinweise je Wert."
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-tax_year", "-rule_version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tax_year", "rule_version"),
                        name="unique_tax_rule_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaxProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tax_year", models.PositiveIntegerField(db_index=True)),
                (
                    "legal_form",
                    models.CharField(
                        choices=[
                            ("sole", "Einzelunternehmen"),
                            ("freelancer", "Freiberufler"),
                            ("ug", "UG (haftungsbeschränkt)"),
                            ("gmbh", "GmbH"),
                        ],
                        default="sole",
                        max_length=20,
                    ),
                ),
                (
                    "small_business",
                    models.BooleanField(default=False, help_text="§19 UStG"),
                ),
                (
                    "other_taxable_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "joint_assessment",
                    models.BooleanField(
                        default=False, help_text="Zusammenveranlagung (Splitting)."
                    ),
                ),
                (
                    "trade_tax_multiplier",
                    models.PositiveIntegerField(
                        default=400, help_text="Hebesatz in %, z. B. 400."
                    ),
                ),
                ("church_tax", models.BooleanField(default=False)),
                (
                    "federal_state",
                    models.CharField(
                        default="BW", help_text="Bundesland-Kürzel.", max_length=2
                    ),
                ),
                (
                    "health_insurance_status",
                    models.CharField(
                        choices=[
                            ("statutory_voluntary", "Freiwillig gesetzlich"),
                            ("private", "Privat"),
                            ("family", "Familienversichert"),
                        ],
                        default="statutory_voluntary",
                        max_length=24,
                    ),
                ),
                (
                    "estimated_monthly_health_insurance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("450.00"), max_digits=10
                    ),
                ),
                (
                    "safety_margin_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=5
                    ),
                ),
                (
                    "prepayments_made",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Bereits geleistete Steuervorauszahlungen.",
                        max_digits=12,
                    ),
                ),
                (
                    "existing_reserve",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Bereits gebildete Rücklage.",
                        max_digits=12,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "tax_year"),
                        name="unique_tax_profile_per_year",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReserveSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("snapshot_date", models.DateField(db_index=True)),
                ("tax_year", models.PositiveIntegerField()),
                (
                    "revenue_ytd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "expenses_ytd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "profit_ytd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "projected_annual_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estimated_income_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estimated_soli",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estimated_church_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estimated_trade_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "trade_tax_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "vat_reserve",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "health_insurance_buffer",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "safety_buffer",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "recommended_reserve",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "existing_reserve",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "reserve_gap",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("calculation_trace", models.JSONField(default=dict)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.workspace",
                    ),
                ),
                (
                    "rule_set",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="finance.taxruleset",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "snapshot_date"),
                        name="unique_reserve_snapshot_per_day",
                    )
                ],
            },
        ),
    ]
