# Generated by Django 5.2.16 on 2026-07-21 15:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finance', '0002_correct_tax_rules_and_corporate_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('manual', 'Manuell erfasst'), ('lexware', 'Aus Lexware synchronisiert')], default='manual', max_length=20)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-transfer_date', '-created_at'],
                'indexes': [models.Index(fields=['workspace', '-transfer_date'], name='finance_res_workspa_004f80_idx')],
            },
        ),
    ]
