# Generated by Django 5.2.16 on 2026-07-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manuell"),
                    ("timer", "Timer"),
                    ("clockodo", "Clockodo"),
                ],
                default="manual",
                max_length=10,
            ),
        ),
    ]
