# Generated by Django 5.2.16 on 2026-07-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0002_alter_timeentry_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manuell'), ('timer', 'Timer'), ('clockodo', 'Clockodo'), ('lexware', 'Lexware')], default='manual', max_length=10),
        ),
    ]
