# Generated by Django 5.2.16 on 2026-07-17 12:52

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                ("legal_form", models.CharField(blank=True, max_length=100)),
                ("owner_name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("address_street", models.CharField(blank=True, max_length=255)),
                ("address_zip", models.CharField(blank=True, max_length=20)),
                ("address_city", models.CharField(blank=True, max_length=120)),
                ("address_country_code", models.CharField(default="DE", max_length=2)),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, help_text="Steuernummer", max_length=50
                    ),
                ),
                (
                    "vat_id",
                    models.CharField(blank=True, help_text="USt-IdNr.", max_length=50),
                ),
                (
                    "small_business",
                    models.BooleanField(
                        default=False,
                        help_text="Kleinunternehmerregelung nach §19 UStG",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=120)),
                ("bank_iban", models.CharField(blank=True, max_length=42)),
                ("bank_bic", models.CharField(blank=True, max_length=11)),
                ("default_currency", models.CharField(default="EUR", max_length=3)),
                (
                    "default_hourly_rate",
                    models.DecimalField(decimal_places=2, default=95, max_digits=10),
                ),
                (
                    "default_payment_term_days",
                    models.PositiveSmallIntegerField(default=14),
                ),
                (
                    "time_rounding_increment_minutes",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0 = no rounding. Otherwise round to this many minutes.",
                    ),
                ),
                (
                    "time_rounding_strategy",
                    models.CharField(
                        choices=[
                            ("nearest", "Nearest"),
                            ("up", "Up"),
                            ("down", "Down"),
                        ],
                        default="nearest",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "workspace",
                "verbose_name_plural": "workspaces",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="staff status"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "avatar_color",
                    models.CharField(
                        blank=True,
                        help_text="Hex colour used for the avatar fallback, e.g. #6366f1.",
                        max_length=7,
                    ),
                ),
                ("locale", models.CharField(default="de-DE", max_length=10)),
                ("time_zone", models.CharField(default="Europe/Berlin", max_length=64)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["email"],
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("readonly", "Read-only"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Workspace selected on login when none is specified.",
                    ),
                ),
                ("invited_at", models.DateTimeField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["workspace__name", "user__email"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="accounts_wo_user_id_6a59e3_idx",
                    ),
                    models.Index(
                        fields=["workspace", "role"],
                        name="accounts_wo_workspa_3e6e69_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "user"), name="unique_workspace_member"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("user",),
                        name="unique_default_workspace_per_user",
                    ),
                ],
            },
        ),
    ]
