# Generated by Django 5.2.16 on 2026-07-17 12:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("lexware", "Lexware Office"),
                            ("clockodo", "Clockodo"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("resource_type", models.CharField(db_index=True, max_length=64)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound (remote → local)"),
                            ("outbound", "Outbound (local → remote)"),
                            ("bidirectional", "Bidirectional"),
                        ],
                        default="inbound",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped (integration disabled)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        default="scheduled",
                        help_text="scheduled | manual | webhook | connect",
                        max_length=32,
                    ),
                ),
                ("is_full_sync", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("records_processed", models.PositiveIntegerField(default=0)),
                ("records_created", models.PositiveIntegerField(default=0)),
                ("records_updated", models.PositiveIntegerField(default=0)),
                ("records_skipped", models.PositiveIntegerField(default=0)),
                ("records_failed", models.PositiveIntegerField(default=0)),
                ("error_summary", models.TextField(blank=True)),
                (
                    "cursor",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Resume point, e.g. {'window_end': '2024-03-01'}.",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "sync job",
                "verbose_name_plural": "sync jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncConflict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("lexware", "Lexware Office"),
                            ("clockodo", "Clockodo"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("resource_type", models.CharField(db_index=True, max_length=64)),
                ("local_object_type", models.CharField(max_length=64)),
                (
                    "local_object_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("local_snapshot", models.JSONField(default=dict)),
                ("remote_snapshot", models.JSONField(default=dict)),
                (
                    "reason",
                    models.CharField(
                        default="concurrent_modification",
                        help_text="concurrent_modification | version_conflict | remote_deleted | unwritable_remote | ambiguous_match",
                        max_length=64,
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved_local", "Resolved — local version kept"),
                            ("resolved_remote", "Resolved — remote version kept"),
                            ("resolved_manual", "Resolved — manually merged"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=24,
                    ),
                ),
                ("resolution", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.workspace",
                    ),
                ),
                (
                    "sync_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conflicts",
                        to="integrations.syncjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "sync conflict",
                "verbose_name_plural": "sync conflicts",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("lexware", "Lexware Office"),
                            ("clockodo", "Clockodo"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                (
                    "external_resource_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Selected headers, credentials scrubbed.",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored (not subscribed / unknown type)"),
                            ("duplicate", "Duplicate (already processed)"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=16,
                    ),
                ),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "dedupe_key",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "signature_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Lexware: RSA-SHA512 verified. Clockodo: token matched.",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "webhook event",
                "verbose_name_plural": "webhook events",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalObjectLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("lexware", "Lexware Office"),
                            ("clockodo", "Clockodo"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True,
                        help_text="Provider-side resource, e.g. 'contact', 'invoice', 'entry'.",
                        max_length=64,
                    ),
                ),
                (
                    "local_object_type",
                    models.CharField(
                        help_text="Django label, e.g. 'crm.Client'.", max_length=64
                    ),
                ),
                ("local_object_id", models.UUIDField(db_index=True)),
                ("external_id", models.CharField(db_index=True, max_length=128)),
                (
                    "external_version",
                    models.CharField(
                        blank=True,
                        help_text="Remote version/revision. Lexware uses an int; Clockodo has none.",
                        max_length=64,
                    ),
                ),
                (
                    "sync_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of the last-synced remote payload; equal hash ⇒ skip write.",
                        max_length=80,
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "last_remote_modified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("deleted_remotely", models.BooleanField(db_index=True, default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "external object link",
                "verbose_name_plural": "external object links",
                "indexes": [
                    models.Index(
                        fields=["provider", "resource_type", "external_id"],
                        name="integration_provide_fec170_idx",
                    ),
                    models.Index(
                        fields=["local_object_type", "local_object_id"],
                        name="integration_local_o_7a26c4_idx",
                    ),
                    models.Index(
                        fields=["provider", "deleted_remotely"],
                        name="integration_provide_fc8362_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "workspace",
                            "provider",
                            "resource_type",
                            "external_id",
                        ),
                        name="unique_external_object_per_workspace",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "workspace",
                            "provider",
                            "resource_type",
                            "local_object_id",
                        ),
                        name="unique_local_object_link_per_provider",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("lexware", "Lexware Office"),
                            ("clockodo", "Clockodo"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "external_organization_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "connection_id",
                    models.CharField(
                        blank=True,
                        help_text="Lexware connectionId — the resourceId carried by token.revoked events.",
                        max_length=128,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("tax_type", models.CharField(blank=True, max_length=32)),
                ("small_business", models.BooleanField(default=False)),
                ("subscription_status", models.CharField(blank=True, max_length=64)),
                ("raw_profile", models.JSONField(blank=True, default=dict)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "provider profile",
                "verbose_name_plural": "provider profiles",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "provider"),
                        name="unique_provider_profile_per_workspace",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="syncjob",
            index=models.Index(
                fields=["provider", "resource_type", "-created_at"],
                name="integration_provide_bc082c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="syncjob",
            index=models.Index(
                fields=["provider", "status", "-created_at"],
                name="integration_provide_b7f343_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="syncconflict",
            index=models.Index(
                fields=["provider", "resolution_status", "-detected_at"],
                name="integration_provide_5498f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["provider", "processing_status", "received_at"],
                name="integration_provide_6b7a39_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["provider", "event_type", "-received_at"],
                name="integration_provide_f59143_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedupe_key__gt", "")),
                fields=("provider", "dedupe_key"),
                name="unique_webhook_dedupe_key",
            ),
        ),
    ]
