# Generated by Django 5.2.16 on 2026-07-17 22:17

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("position", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("mobile", models.CharField(blank=True, max_length=50)),
                (
                    "preferred_channel",
                    models.CharField(
                        choices=[
                            ("email", "E-Mail"),
                            ("phone", "Telefon"),
                            ("mobile", "Mobil"),
                            ("other", "Sonstiges"),
                        ],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-is_primary", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="ClientNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("note", "Notiz"),
                            ("call", "Telefonat"),
                            ("meeting", "Termin"),
                            ("email", "E-Mail"),
                        ],
                        default="note",
                        max_length=10,
                    ),
                ),
                ("follow_up_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                ("legal_form", models.CharField(blank=True, max_length=100)),
                (
                    "client_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-vergeben (K-1001, …) wenn leer.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prospect", "Interessent"),
                            ("active", "Aktiv"),
                            ("paused", "Pausiert"),
                            ("former", "Ehemalig"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=120)),
                ("website", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("billing_street", models.CharField(blank=True, max_length=255)),
                ("billing_zip", models.CharField(blank=True, max_length=20)),
                ("billing_city", models.CharField(blank=True, max_length=120)),
                ("billing_country_code", models.CharField(default="DE", max_length=2)),
                ("shipping_street", models.CharField(blank=True, max_length=255)),
                ("shipping_zip", models.CharField(blank=True, max_length=20)),
                ("shipping_city", models.CharField(blank=True, max_length=120)),
                ("shipping_country_code", models.CharField(blank=True, max_length=2)),
                ("tax_number", models.CharField(blank=True, max_length=50)),
                ("vat_id", models.CharField(blank=True, max_length=50)),
                (
                    "default_hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leer ⇒ Workspace-Standard.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "payment_term_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("notes", models.TextField(blank=True)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=40),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("acquisition_source", models.CharField(blank=True, max_length=120)),
                ("customer_since", models.DateField(blank=True, null=True)),
                ("archived", models.BooleanField(db_index=True, default=False)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClientActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("client_created", "Kunde angelegt"),
                            ("contact_added", "Ansprechpartner hinzugefügt"),
                            ("note_added", "Notiz erstellt"),
                            ("project_created", "Projekt angelegt"),
                            ("task_completed", "Aufgabe abgeschlossen"),
                            ("time_tracked", "Zeit erfasst"),
                            ("status_changed", "Status geändert"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="crm.client",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "client activities",
                "ordering": ["-occurred_at"],
            },
        ),
    ]
