# Generated by Django 5.2.16 on 2026-07-17 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("crm", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clientactivity",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="clientactivity",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="accounts.workspace",
            ),
        ),
        migrations.AddField(
            model_name="clientcontact",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="crm.client",
            ),
        ),
        migrations.AddField(
            model_name="clientcontact",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="accounts.workspace",
            ),
        ),
        migrations.AddField(
            model_name="clientnote",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clientnote",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_notes",
                to="crm.client",
            ),
        ),
        migrations.AddField(
            model_name="clientnote",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="accounts.workspace",
            ),
        ),
        migrations.AddField(
            model_name="clientactivity",
            name="note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="crm.clientnote",
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["workspace", "status", "archived"],
                name="crm_client_workspa_f72e91_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_number", ""), _negated=True),
                fields=("workspace", "client_number"),
                name="unique_client_number_per_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="clientcontact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("client",),
                name="unique_primary_contact_per_client",
            ),
        ),
    ]
